---
name: Analyze apk
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
 
  workflow_dispatch:
jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
      - name: Execute exodus-standalone
        uses: docker://exodusprivacy/exodus-standalone:v1.4.0
        with:
          args: /github/workspace/apk/app.apk
